/*
 * File: FEMhub.ModuleBasicWindow.ui.js
 * Date: Sun Dec 12 2010 20:44:18 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('FEMhub');
FEMhub.ModuleBasicWindowUi = Ext.extend(Ext.Window, {
    title: 'Module Basic',
    width: 591,
    height: 492,
    layout: 'fit',
    boxMinHeight: 580,
    boxMinWidth: 880,
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                title: '',
                ref: 'main_tabs',
                id: 'main_tabs',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Geometry',
                        layout: 'fit',
                        tpl: '',
                        html: '',
                        ref: '../geometry_tab',
                        id: 'geometry_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Operate on Nodes',
                                    ref: '../../../nodes_button'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Edges'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Subdomains'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Model',
                        layout: 'border',
                        autoScroll: true,
                        ref: '../model_tab',
                        id: 'model_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Boundary Conditions',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Add new...',
                                                menu: {
                                                    xtype: 'menu',
                                                    items: [
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Dirichlet'
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Neumann'
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Newton'
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'List:'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Materials',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Add new...'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'List:'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'panel',
                                region: 'west',
                                width: 142,
                                autoScroll: true,
                                split: true,
                                ref: '../../model_parameters'
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        title: 'Computation',
                        activeTab: 0,
                        ref: '../computation_tab',
                        id: 'computation_tab',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Setup',
                                ref: '../../computation_setup',
                                id: 'computation_setup',
                                bbar: new FEMhub.Statusbar({
                                    busyText: '',
                                    defaultText: '',
                                }),
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        value: 'Number of mesh refinements:'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 0,
                                        ref: '../../../Init_ref_num',
                                        id: 'Init_ref_num'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Polynomial degree:'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 4,
                                        ref: '../../../Init_p',
                                        id: 'Init_p'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Matrix solver:'
                                    },
                                    {
                                        xtype: 'textfield',
                                        value: 'umfpack',
                                        ref: '../../../Matrix_solver',
                                        id: 'Matrix_solver'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Run',
                                        iconCls: '',
                                        cls: '',
                                        iconAlign: 'bottom',
                                        ref: '../../../computation_run'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Log',
                                ref: '../../computation_log',
                                id: 'computation_log'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Postprocessing',
                        autoScroll: true,
                        layout: 'fit',
                        ref: '../postprocessing_tab',
                        id: 'postprocessing_tab',
                        items: [
                            {
                                xtype: 'panel',
                                title: '',
                                autoScroll: true,
                                layout: 'fit',
                                unstyled: true,
                                ref: '../../postproc_panel'
                            }
                        ],
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Point Values'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Line Integrals'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Volume Integrals'
                                }
                            ]
                        }
                    }
                ]
            }
        ];
        FEMhub.ModuleBasicWindowUi.superclass.initComponent.call(this);
    }
});
