/*
 * File: FEMhub.ModuleBasicWindow.ui.js
 * Date: Wed Dec 08 2010 02:19:10 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('FEMhub');
FEMhub.ModuleBasicWindowUi = Ext.extend(Ext.Window, {
    title: 'Module Basic',
    width: 591,
    height: 492,
    layout: 'fit',
    boxMinHeight: 580,
    boxMinWidth: 880,
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                ref: 'main_tabs',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Geometry',
                        layout: 'fit',
                        tpl: '',
                        html: '',
                        ref: '../mesheditor_panel',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Operate on Nodes',
                                    ref: '../../../nodes_button'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Edges'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Subdomains'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Model',
                        layout: 'border',
                        ref: '../model_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'New Boundary Condittion'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'New Mateiral Property'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Run',
                                    iconCls: 'femhub-add-worksheet-icon',
                                    cls: 'x-btn-text-icon',
                                    ref: '../../../run_button'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'panel',
                                region: 'center',
                                autoScroll: true,
                                ref: '../../model_solution'
                            },
                            {
                                xtype: 'panel',
                                region: 'west',
                                width: 142,
                                autoScroll: true,
                                split: true,
                                ref: '../../model_parameters'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Postprocessing',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Point Values'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Line Integrals'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Volume Integrals'
                                }
                            ]
                        }
                    }
                ]
            }
        ];
        FEMhub.ModuleBasicWindowUi.superclass.initComponent.call(this);
    }
});
